### ISSUE TITLE
When you deprecate contentType in favor of headers, please make headers an object and not an array of tuples

### ISSUE THREAD

**Issue by DreamwareDevelopment** [brillout/vite-plugin-ssr#1130]
### Description

I haven't seen headers as an array of tuples before. The DX is odd and there's a perf implication of having to iterate headers just to find one (albeit minor because headers are small). Is there a particularly good reason not to return an object from the httpResponse of renderPage? Maybe it's worth just converting it into an object on the plugin side so that callers don't have to?

**Comment by brillout** [comment]
A header can have multiple values and, therefore, the normalized value of a header should be a list.

I did consider returning an object of arrays instead of an array of arrays, but I ended up with the latter. While I agree with you that it's easier to use an object, there are a lot more considerations to it (e.g. it seems that an object of arrays isn't as widely supported).

Providing headers as an array of arrays is standard and you can easily convert it to the Fetch API `Header` object:

```js
const headers = new Headers(pageContext.httpResponse.headers)
```

**Comment by DreamwareDevelopment** [comment]
Ah I didn't know this was the standard. Thanks for the response!

**Comment by brillout** [comment]
I wouldn't say it's *the* standard (I don't think there is one), but it does seem somewhat standard (e.g. Fetch API and therefore Cloudflare Workers support it).

**Comment by DreamwareDevelopment** [comment]
I'm working with Go Fiber in another microservice and it doesn't support duplicate headers and just uses a map, that's where the confusion is coming from.
