### ISSUE TITLE
Partial Hydration

### ISSUE THREAD

**Issue by OfekA** [brillout/vite-plugin-ssr#167]
## Background & Motivation
Partial hydration is a key differentiator between classical `MPAs`/`Astro` and tools like `vite-plugin-ssr`/`Next`/`Nuxt`.
Partial hydration is key to achieving high lighthouse scores and improve performance in general. 

Most projects that require SSR have prioritized SEO and instant loading of content for their users, whatever the network or device conditions are, instead of doing it all client-side, so it only makes sense that tools that allow SSR also allow partial hydration.

`Astro` will soon have SSR (it's on their roadmap) and they will compete a lot on mind share. 

For more context, read [RyanCarniato](https://twitter.com/RyanCarniato)'s tweets, he is talking about it a lot, he is the author of SolidJS and working on the Marko team at eBay: https://twitter.com/RyanCarniato/status/1442715830471389194?s=20

## Proposed Solution
I think the _islands approach_ to partial hydration is the future, as in: 

- No hydration by default
- Hydrate only the parts the developer specifies

This approach has been highly popularized by `Astro`. Their API is also very straightforward.
Here is another attempt to use Vue, Vite with partial hydration, inspired by Astro: https://github.com/ElMassimo/iles

## Next steps
I think we should first discuss: 

- Does this falls into the scope of `vite-plugin-ssr`?
- If so, detailed design on how this should be integrated

Let me know what you think!

**Comment by brillout** [comment]
👍

**Comment by ElMassimo** [comment]
Would love to collaborate on this! I'm wrapping up a new release for [îles](https://github.com/ElMassimo/iles), and have a roadmap that will take a few weeks before I start thinking about supporting SSR, but it's certainly possible with the current architecture.

In particular, packages such as `@islands/hydration` could be reused.

**Comment by ryansolid** [comment]
Yeah it's an interesting topic. I consider this a transitional one. Current thinking and approaches are temporary as they don't lend to a universal solution as of yet. Part of this is hydration and lazy loading boundaries are being conflated. Other part is natural mismatch between app structure of SPA vs MPA. You can't hydrate part of a SPA without hydrating its parent. Basically where are today these are conflicting mentalities.

But having tools that provide these manual islands gives a lot of immediate value. I think support for streaming plus partial hydration is where these really come together but it's also the trickiest to coordinate since ideally each island wouldn't be blocking the page and you need to basically handle all the streams coming together. 

Biggest consideration is how to present true MPA mode versus SSR+SPA, since for partial hydration to work you need actual MPA. Honestly I think the current tools like Astro are doing a good job of paving the way for MPA but I think that unifying the developer experience so these different architectures are seamless or at least easy to make decisions about is probably the biggest challenge here. Beyond the tools there are different sort of considerations and app architectures that come from it (like MPA tend to have less other JS libraries even when using the common suspects), so much that it needs to be a deliberate decision per page with greater impact than just switching a mode toggle. You write your code differently and that always comes with mental cost.

**Comment by spacedawwwg** [comment]
> Would love to collaborate on this! I'm wrapping up a new release for [îles](https://github.com/ElMassimo/iles), and have a roadmap that will take a few weeks before I start thinking about supporting SSR, but it's certainly possible with the current architecture.
> 
> In particular, packages such as `@islands/hydration` could be reused.

@ElMassimo how much effort do you think it would take to extract the hydration part of Iles into its own package?

**Comment by mmm8955405** [comment]
From October last year to August this year！  Are there any results?

**Comment by mmm8955405** [comment]
I am very disappointed with the official svelte / sveltekit team! They don't deal with any problems. All issues related to Vue \ react will be closed. Or is partial hydration really difficult? Will it take more than a year for there to be no breakthrough?
[https://github.com/sveltejs/svelte/issues/7757](url)

**Comment by fgnass** [comment]
Regarding the partial hydration stuff you can also take some inspiration from https://capri.build as it is based on Vite, too. It would be great if the next version of Capri could be built on top of `vite-plugin-ssr`!

**Comment by mmm8955405** [comment]
> Regarding the partial hydration stuff you can also take some inspiration from https://capri.build as it is based on Vite, too. It would be great if the next version of Capri could be built on top of `vite-plugin-ssr`!

Well, thank you very much. Go and study now

**Comment by brillout** [comment]
> Capri could be built on top of `vite-plugin-ssr`!

That'd be nice indeed.

Also check out [Astro](https://astro.build/), which is built on top of Vite as well.

I'm closing this ticket because it's more of a user land thing. Partial Hydration should, in principle, already be possible today when using vps.
