### ISSUE TITLE
vite-plugin-vercel

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#222]
vite-plugin-ssr already supports Vercel https://vite-plugin-ssr.com/vercel but it would be lovely to have a `vite-plugin-vercel` so that the entire Vite ecosystem can benefit.

Discussoin about this: https://discord.com/channels/815937377888632913/815937377888632916/915547793987350548

I've secured the npm package and I'm happy to give it away.

**Comment by brillout** [comment]
Neat.

Let me know if you are up for creating a little Vite plugin wrapping this. We'll discuss the high-level design of it.

**Comment by patryk-smc** [comment]
I have a bit too much on my plate at the moment to work on this, but will
let you know if I get some spare time. I guess we will be refining the
deployment process anyway before going to production.

Ściskam dłoń,
Patryk Jakubik
Tale Commerce <https://talecommerce.pl>

**Comment by brillout** [comment]
👍

**Comment by magne4000** [comment]
I'm currently beginning to work on this subject, mostly because I need this for [ISR](https://vercel.com/docs/concepts/next.js/incremental-static-regeneration).

Should we have a underlying package not tied to `vite` ecosystem (like a `vercel-fs-api` package)?
- It would store types definitions for manifest files
- It could have helpers (not sure if even useful)
Beside types (that should be store inside `@vercel/node` IMO), I'm not seeing any real use case for this, do someone think of one?

Should `vite-plugin-vercel` work without `vite-plugin-ssr`? If so, how should it behave (I'm not familiar with vite internals yet)?
If both are present, here is how I see things:
- Add `api/*` to compilation stages
- Move/copy `dist/client` to `.output/server/pages` + generate `.output/routes-manifest.json`
- Move/copy `dist/client/assets` to `.output/static`
- Move/copy `dist/client/img` to `.output/static/img` + generate optional `.output/images-manifest.json`
- Generate `.output/server/pages/**/[function].nft.json` files for dependencies if any
- Generate optional `.output/functions-manifest.json` if specified in config somewhere?

And regarding new ISR feature:
- Generate `.output/prerender-manifest.json` for `*.page.server.[tj]sx?` that exports prerender with new params (could be same params as next https://vercel.com/docs/concepts/next.js/incremental-static-regeneration)

**Comment by brillout** [comment]
> Should we have a underlying package not tied to vite ecosystem (like a vercel-fs-api package)?

I agree and `vite-plugin-vercel` would ony be a thin wrapper on top of it. FYI: https://github.com/vitejs/vite/issues/5936.

There is already some prior work to deploy vps with Vercel's FS api: https://github.com/brillout/vite-plugin-ssr/blob/master/examples/vercel/vercel/deploy.sh.

As for the rest, sounds good.

I'm very much looking forward to this. Feel free to show me a draft.

**Comment by magne4000** [comment]
I realise that `vite-plugin-ssr prerender` should probably be moved into an option of the plugin itself like:
```ts
export default defineConfig({
    plugins: [ssr({
        prerender: true
    })],
});
```

This plugin should then be able to move generated html files to the right `.output/server/pages` directory.

**Comment by brillout** [comment]
Yes

**Comment by magne4000** [comment]
Here is [the repo](https://github.com/magne4000/test-vite-vercel-plugin) with the first working tests. What does it do for now (or don't):
- Needs `vite-plugin-ssr` to work
  - TODO: make `vite-plugin-ssr` optional
- `prerender` is called programmatically to generates `.output/server/pages`
  - NOTE: Handy to be able to directly generate to `.output/server/pages` directory, but let's discuss if this should be handled by `vite-plugin-ssr` through config instead
  - TODO: make this configurable
- Copy of `vite-plugin-ssr` client files to `.output/assets`
- Generate a unique bundle through `esbuild` for each `/api` endpoint into `.output/server/pages`
  - TODO: logic/config to choose between `.output/server/pages` and `.output/server/pages/api`
  - TODO: support `.output/server/pages/**/[function].nft.json` if endpoints are sharing code
- `dynamicRoutes` must be configured directly in the plugin instead of `rewrites` in `vercel.json`
  - with an additional  `ssr?: boolean` prop to determine which endpoints are linked to `vite-plugin-ssr`
- Following manifests are generated:
  - `functions-manifest.json`: tweak functions config, like `maxDuration`
    - TODO: make this configurable
  - `routes-manifest.json`: copy user provided `dynamicRoutes` here
    - TODO: add more user provided config
  - `prerender-manifest.json`: generates `routes` for each page, and `dynamicRoutes` for each `ssr` endpoint
    - does not handle `dataRoute` for now
    - All pages are SSG and ISR for now (working for the demo, check _/about_, it should regenerate after 30 seconds :tada:):
      - TODO: should be able to ingest config (like "is ISR enable for this page?" or "what is the `initialRevalidateSeconds` value, globally or for each specific page")
      - TODO: ISR does not work if static page is not generated by SSG. This is currently not handled
- asserts needs to be added
- TODO: support `.output/images-manifest.json`

Deployed at https://test-vite-vercel-plugin.vercel.app/

**Comment by patryk-smc** [comment]
Hey @magne4000 that repo seems to be private ;)

**Comment by magne4000** [comment]
oups :hand_over_mouth:. Fixed

**Comment by brillout** [comment]
How about this?

```js
// vite.config.js

export default {
  // These settings can be set by the user or by another plugin such as vps
  vercel: {
    isr: {
      initialRevalidateSeconds: 30,
      prerenderHook: /* prerender function called by vite-plugin-vercel */,
    },
    apiEndpoints: ['./api/foo.js'],
  }
}
```

vps can set some of these settings on behalf of the user, such as:
 - `vite.config.js#vercel.prerender`: vps provides a thin wrapper around its `prerender` CLI.
 - `vite.config.js#vercel.apiEndpoints`. vps provides something like https://github.com/brillout/telefunc-vercel-ssr/blob/master/api/ssr.js, so that the user doesn't have to write it. Further tools, such as Telefunc, can also add themselves: https://github.com/brillout/telefunc-vercel-ssr/blob/master/api/telefunc.js.

This allows vpc to be decoupled from vps.

It also enables decoupled development: what we can do is to first work on an example where these settings are all set by the user's `vite.config.js`. We then move the prerender CLI wrapper and the api endpoint into vps's source code.

Thoughts? Also thoughts about https://github.com/vitejs/vite/issues/5936?

I gave you full privilege for https://www.npmjs.com/package/vite-plugin-vercel.

**Comment by magne4000** [comment]
Using `vite.config.js` is fine with me, it should ensure common API between all the vps plugins.

> vite.config.js#vercel.prerender: vps provides a thin wrapper around its prerender CLI.

👍 

> vite.config.js#vercel.apiEndpoints. vps provides something like https://github.com/brillout/telefunc-vercel-ssr/blob/master/api/ssr.js, so that the user doesn't have to write it. Further tools, such as Telefunc, can also add themselves: https://github.com/brillout/telefunc-vercel-ssr/blob/master/api/telefunc.js.

I like the idea! We'll have to dig a little further, like how can I add specific behaviour (like redirect behaviour, setcookie, custom headers, etc. based on pageContext)? (Writing this I realize that in the handler, the only thing I want to customize are HTTP responses)

> It also enables decoupled development

We should even be able to easily share logic between dev (e.g. express) and prod (e.g. vercel)

> what we can do is to first work on an example where these settings are all set by the user's vite.config.js

I'll probably have time next week to try that

> Also thoughts about https://github.com/vitejs/vite/issues/5936?

Yep, It would be easier to write this plugi n if we had a single process, that's sure

> I gave you full privilege for https://www.npmjs.com/package/vite-plugin-vercel.

🙏

**Comment by brillout** [comment]
The thin wrapper around vps's `prerender` CLI would provide page-specific configs, so that the user can do this:

```js
// /pages/product.page.js

// Overrides the default
export const initialRevalidateSeconds = 10

// The usual stuff
export { Page }
// ...
```

> share logic between dev (e.g. express) and prod (e.g. vercel)

@cyco130 is actually working on that (https://github.com/hattipjs/hattip &mdash; there isn't any documentation yet).

**Comment by magne4000** [comment]
Prerendering code uses both `vite-plugin-ssr` and `vite-plugin-vercel`. The sensible way would be to put it in another repo (or monorepo package), but I think it would be better that if both `vite-plugin-ssr` and `vite-plugin-vercel` are installed, the user does not have to manually set the prerender function in `vite.config.js`.
So the question is, where do we put those specific prerender functions? I lean a little towards storing those in their respective framework (i.e. in `vite-plugin-ssr`, `telefunc`, etc.)

**Comment by rauchg** [comment]
This sounds very exciting. Thanks for everyone who's helping out with this, and we look forward to supporting y'all and Vite from our side.

**Comment by brillout** [comment]
@rauchg Much appreciated 👍. We actually have some question over there https://github.com/vercel/vercel/discussions/7573.

**Comment by brillout** [comment]
Neat 👌.

>  Let me know if you have some remarks on it

Little typo here https://github.com/magne4000/test-vite-vercel-plugin/blob/41af424c620b14c61697ea838404dfc952992474/packages/vercel/src/types.ts#L117 (~~ssr~~ isr) but other than that looks good from first sight. I'm not all too familiar with Vercel so I can't say whether the naming makes sense.

You are using vps internals which is fine but we should add an integration test, like we already have for Cloudflare Workers (e.g. https://github.com/brillout/vite-plugin-ssr/blob/master/examples/cloudflare-workers/.test-wrangler.spec.ts). Is there a way to try a Vercel deploy locally without actually publishing the app?

**Comment by magne4000** [comment]
> Little typo here https://github.com/magne4000/test-vite-vercel-plugin/blob/41af424c620b14c61697ea838404dfc952992474/packages/vercel/src/types.ts#L117 (~~ssr~~ isr) but other than that looks good from first sight. I'm not all too familiar with Vercel so I can't say whether the naming makes sense.

`initialRevalidateSeconds` is tied to ISR indeed, but itself ISR is tied to SSR + Static generation (it needs both). So it can make sense anywhere. `prerender` on the other is tied to Static Generation only (I reused the [terms defined by Next.js](https://nextjs.org/docs/basic-features/pages)). More generally, all those concepts are under the prerendering category. perhaps we should name that `prerendering` instead?

> You are using vps internals which is fine but we should add an integration test, like we already have for Cloudflare Workers (e.g. https://github.com/brillout/vite-plugin-ssr/blob/master/examples/cloudflare-workers/.test-wrangler.spec.ts). Is there a way to try a Vercel deploy locally without actually publishing the app?

Sadly no. What I was thinking of doing is test the content of output generated files. Not the ideal test scenario, but it would ensure good regression tests at least.

**Comment by brillout** [comment]
My thinking is that a user that does only SSG wouldn't use Vercel in the first place. So it seems to me that prerendering is always tied to ISR? And, on the flip side, if the user doesn't define a prerender function then he doesn't do ISR.

Ok, and yes, regression tests should be enough for now.

**Comment by magne4000** [comment]
> My thinking is that a user that does only SSG wouldn't use Vercel in the first place. So it seems to me that prerendering is always tied to ISR?

I can see use cases where you have a mix of SSG and SSR but not necessarily ISR. And for those cases you'll need a prerender function. It assumes less about user's intententions to put the prerender function in something more generic than `isr` IMO

> And, on the flip side, if the user doesn't define a prerender function then he doesn't do ISR.

**Comment by brillout** [comment]
Makes sense.

How about flattening then? I.e. defining `initialRevalidateSeconds` and `prerender` directly on the config root.

**Comment by magne4000** [comment]
Indeed. Simpler I don't see drawbacks as the configuration is quite minimal, this is probably the way to go :+1:

**Comment by brillout** [comment]
> Route functions are called on every request:

Yes and no.

They are called for every URL in order to determine the `pageContext._pageId`.

And, yes, on the server-side they are also called for every request, but only to determine `pageContext.routeParams`. The entire mapping URL -> `pageContext._pageId` is already known at build-time.

So I don't think route functions are any problem for ISR. Note that route functions can be used today with SSG (by using the `prerender()` hook, see https://vite-plugin-ssr.com/prerender#for-providing-urls).

**Comment by brillout** [comment]
> And, yes, on the server-side they are also called for every request, but only to determine `pageContext.routeParams`.

And this is actually only the case for SSR. For SSG, there is no server-side JavaScript execution.

 - SSR -> `pageContext.routeParams` is determined dynamically at run-time.
 - SSG -> `pageContext.routeParams` is determined statically at build-time.

**Comment by magne4000** [comment]
Ok thanks, I still need some fallback rule then I guess

**Comment by brillout** [comment]
AFAICT, the only logic here is: is this a URL of a static asset? Then serve that static asset, otherwise do SSR.

So you somehow need to probe whether the URL was already pre-rendered.

**Comment by magne4000** [comment]
That's indeed what the fallback rule is for, ignore `/assets/*`, and also `/api/*` in the case of vercel -> catch all the rest (`^/((?!assets/)(?!api/).*)$`).
But for now I didn't even needed this fallback rule, as I could determine everything from `prerender` callback (and mostly globalContext).
So the behavior will likely be: If you do not have any `.page.route` function, no need for a fallback rule.

**Comment by magne4000** [comment]
You can check all use cases I could think of https://test-vite-vercel-plugin.vercel.app/

**Comment by brillout** [comment]
> If you do not have any `.page.route` function, no need for a fallback rule.

I don't see why route functions need special treatment.

I don't see a difference between a route string `/product/:id` and a route function `pageContext => { const parts = pageContext.urlPathname.split('/'); if (parts[0]==='product') return { routeParams: { id: parts[1] }}}`. Architecturally it's the same.

**Comment by magne4000** [comment]
I see what you mean. I was mislead by the fact I had trouble having a working catch-all rule through `routes-manifest.json`. But now that I found a solution, it should be the only rule in this file.

**Comment by magne4000** [comment]
I have another ISR specific use case.
ISR allow me to prerender part of the files at build time, and other files on access.

Lets say I have the following prerender function:
```ts
export function prerender() {
  return ['/product/a', '/product/b']
}
```
If I access those, statically generated files are served, and potentially they are also updated on the background if `initialRevalidateSeconds` has passed.

But what happens if I access `/product/c`? Currently it's rendered via SSR.
But Vercel has the possibility to serve the page through SSR while also saving it as a static file, so that next call to `/product/c` serves the static file (it's the actual use case that's of interest for me).

For that, I need a way to guess which URLs need to be ISR at build time, even when not prerendered (in this case `/product/:productId`).

I could leverage `.page.route` default export for that:
- If route is a string and `initialRevalidateSeconds` is exported in `.page` -> ISR url
- else -> SSR url

We could also have some new exported value just for ISR routes

> We could let the user add another export next to the route function with a route hint (same as route string). That way one can still benefit from route functions for ~~non fallback/complex cases~~ ISR

Relevant for this use case

**Comment by brillout** [comment]
I assume that the page would be SSR'd before being added to the ISR cache.

In that case a custom export should do the trick:

```js
// product.page.js

export const isr = true
```

You can then read `pageContext.pageExports.isr` to decide whether to populate the ISR cache.

**Comment by magne4000** [comment]
> I assume that the page would be SSR'd before being added to the ISR cache.

Yes, but I need to generate a [route regex at build time](https://vercel.com/docs/file-system-api#configuration/pre-rendering/supported-properties/dynamic-routes) that describes all possible ISR routes.

I can't just tell Vervel to cache a page during SSR rendering

**Comment by brillout** [comment]
I'd suggest requiring the user to not use route functions when using ISR.

Anyways, route functions are usually used for dynamically determining which page should be rendered (e.g. auth header cookie) which doesn't make sense with ISR.

**Comment by magne4000** [comment]
Agreed. So to be sure we're on the same page, here's how I see all of this working:

**ISR enabled if:**
- `.page` exports `initialRevalidateSeconds`
- and one of the following is true:
  - page is prerendered
  - page is using filesystem routing (no `.page.route` file)
  - page is using route string

**Comment by brillout** [comment]
Agreed.

One small nitpick:

> * `.page` exports `initialRevalidateSeconds`

How about if `.page` has `export const isr = true` or `export const isr = { initialRevalidateSeconds: 10 }`? Little bonus: it doesn't conflict with the global `initialRevalidateSeconds` value.

**Comment by magne4000** [comment]
I think it would be better to remove the default `initialRevalidateSeconds`. Vercel ISR has no intention to be generic, so a default value does not really make sense IMO. Having a `export const isr = { initialRevalidateSeconds: 10 }` in kinda more portable though if any other provider does ISR, but I like the simplicity of just having `initialRevalidateSeconds`. What do you think?

**Comment by brillout** [comment]
The use case I've in mind for ISR is Stack Overflow or Reddit. Having millions of pages that cannot be pre-rendered at build-time.

For these websites I can see a default value to make sense and `/user/:id` and `/product/:id` would probably share the same default value.

**Comment by magne4000** [comment]
Good point, let's go for `export const isr` then :+1:

**Comment by magne4000** [comment]
`v2` of Vercel's File System API has been deprecated, they are now working on a `v3` https://github.com/vercel/community/discussions/530

**Comment by brillout** [comment]
Done https://github.com/magne4000/vite-plugin-vercel by @magne4000 💯. It even supports ISR.
