### ISSUE TITLE
Built in Vite env vars seem incorrect in prerender hook

### ISSUE THREAD

**Issue by gryphonmyers** [brillout/vite-plugin-ssr#25]
Repro Steps:
1) Add a console.log of `import.meta.env` from inside a page's prerender hook
2) Run prerender process, e.g. `cross-env NODE_ENV=production && npm run build && vite-plugin-ssr prerender --clientRouter`
3) Observe that logged env indicates the following:

```
MODE: 'production'
DEV: true
PROD: false
```

Expected Results:
Having specified NODE_ENV=production, I would expect DEV=false, PROD=true. Additionally, I would expect SSR=true to come through, but it is not showing up at all.

**Comment by brillout** [comment]
Seems like a Vite bug. I will have a look.

**Comment by brillout** [comment]
Couldn't reproduce. The output in https://github.com/brillout/vite-plugin-ssr/commit/764e8e5d9da28e5146b10c0dd8d8ef60c6d746b0 is correct.

Note that your `cross-env NODE_ENV=production` has no effect in your `cross-env NODE_ENV=production && npm run build && vite-plugin-ssr prerender --clientRouter`. Use `cross-env` without `&&`: https://github.com/brillout/vite-plugin-ssr/commit/764e8e5d9da28e5146b10c0dd8d8ef60c6d746b0#diff-3ae58cd0dc48e9afc5345bcd388b6f82b75345c9fd156f5bd3c71cb92037aa64R6. If you were to add `&&` like this `"prod:server": "cross-env NODE_ENV=production && ts-node ./server"` then it wouldn't work.

But that besides the point since it should work nevertheless and simply doing `npm run build && vite-plugin-ssr prerender --clientRouter` should work.

**Comment by gryphonmyers** [comment]
Oh dear. I will try again with the commit you have referenced to see if I can figure out why I was getting different results.

**Comment by brillout** [comment]
No worries. The commit lives in the `reprod-25` branch https://github.com/brillout/vite-plugin-ssr/tree/reprod-25.

**Comment by gryphonmyers** [comment]
OK now I am getting DEV: false, PROD: true, which would be correct, however I am still not seeing SSR populated at all. Were you seeing evidence of SSR env being set inside of prerender hooks as well?

**Comment by brillout** [comment]
Yes I can confirm that the SSR env is missing in prod. I'm confident the problem is on Vite's side. It should be easy to reproduce on https://github.com/vitejs/vite/tree/main/packages/playground/ssr-vue.

**Comment by gryphonmyers** [comment]
OK going to go ahead and close this then. For clarity, I believe the fix here was removeing `&&` in my npm script per brillout's suggestion.
