### ISSUE TITLE
<style> tags are getting transformed into <script> tags

### ISSUE THREAD

**Issue by iMrDJAi** [brillout/vite-plugin-ssr#311]
Instead of including CSS in the server rendered HTML as is, it's getting replaced by module scripts that inject it into the DOM, causing a flash of unstyled content every time the page gets loaded.

Are there any solutions for that?

**Comment by brillout** [comment]
This is expected.

> causing a flash of unstyled content

Make a **minimal** reproduction on of top of one of the examples/boilerplates, and I'll have a look.

**Comment by iMrDJAi** [comment]
@brillout https://github.com/iMrDJAi/vps-bug-minimal-reproduction

Open the about page first (`localhost:3000/about`), you'll see a minimal reproduction of the bug.
I discovered another related bug in the index page (`localhost:3000/`), check the console and you'll see.

**Comment by brillout** [comment]
👍 

The root cause is the HTML transformation done by Vite. The new vps 0.4 version skips the Vite's HTML transformer, so it should work with vps 0.4.

You can have a look at the examples of the `0.4` branch to get started.

You'll still get a little bit of style flashing; but that's inherent to using React for generating style tags.

**Comment by brillout** [comment]
`npm info vite-plugin-ssr` to get the latest 0.4 beta (currently `0.4.0-beta.12`)

**Comment by iMrDJAi** [comment]
@brillout Happy to hear that! Thank you for your efforts <3
