### ISSUE TITLE
Microfrontend

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#336]
### Description

There is interest in using vps for a microfrontend archtiecture.

CC @wheerd @j0weiss

**Comment by lampewebdev** [comment]
I'm also looking into vite/vue/ssr/microfrontends

**Comment by brillout** [comment]
I care about team scalability. But I'm sceptical microfrontends to be the right approach.

I'm happy to be shown wrong. The best would probably be to provide a concrete example (or even better a real life example) where I can see and understand how a microfrontend architecture helps.

**Comment by brillout** [comment]
The way I would tackle this is to have the frontend to be continuously CI'd, deployed, and eventually staged. So that all teams can re-deploy it at any time with confidence.

Then it's about properly structuring the frontend repository so that each team owns specific parts of that repository.

Would that work or am I missing something?

**Comment by lampewebdev** [comment]
> The way I would tackle this is to have the frontend to be continuously CI'd, deployed, and eventually staged. So that all teams can re-deploy it at any time with confidence.  

This would work but this means that this eventually staged deploy must be somehow orchestrated with all the teams. 
With Microfrontends this is not really needed since one team can just deploy when its ready so the teams do not need to re-deploy. The biggest win here is 1 team needs to deploy not N teams.

> Then it's about properly structuring the frontend repository so that each team owns specific parts of that repository.

Sure you can have both a mono-repo and microfrontends. 
 
> Would that work or am I missing something?
This in general would work but its hard to A/B test in a quick way without a big investment in all teams.

**Comment by brillout** [comment]
I'd use a platform like Vercel and Netlify that allow to preview the deploy of each commit.

As for A/B testing I'd then use Git branches for that.

Continous integration, staging, and deploy has the momentum; it seems to be the future.

Whereas microfrontend seems to be a losing proposition.

That's why I'm reluctant to invest in that direction. That said, if there is a microfrontend architecture that would require only little changes on vps's side, I'd be open for it.

Feel free to dig and come back with a concrete proposition of how vps would need to change.

And feel free to object to any of my arguments.

I'm closing this ticket in the meantime. I'll re-open it if someone can convince me.

**Comment by leonmondria** [comment]
I agree with both :)

So I think it depends on the ambitions of the project: if you expect to grow and split into multiple teams the best approach is to go for microservices. 

A lot of problems can be tackled with structuring processes, CI/CD, canary releases and a lot of discipline, but there's a tipping point where that wont be enough anymore.

But I think the question should be: what is the "responsibility" of VPS in this?

If you go for either a horizontal or vertical split in microservices, the way you integrate microservices should be the responsibility of the composer, not the microservice that uses VPS.

If the composer has trouble integrating the microservice because it uses VPS, we should identify the actual problem and try to fix that.

As we speak I'm trying out some proof of concepts on this subject, if I come up with a problem I'll come back here but for now I think it should not be the responsibility of VPS.

Anyways, great discussion and keep up the good work!

**Comment by brillout** [comment]
That makes sense to me.

Also, just to be clear, if someone comes up with a specific feature request and explains how it helps scaling, then I'll definitely consider it. So feel free to propose feature requests here, regardless of my initial reservations.

A lot of companies use VPS for its flexibility/scalability &mdash; I care about this.
