### ISSUE TITLE
SPA mode + Tailwind

### ISSUE THREAD

**Issue by brillout** [brillout/vite-plugin-ssr#408]
### Description

Tailwind works in SSR mode but @AaronBeaudoin is reporting that it doesn't work in SPA mode.

Seems to be vps related since Tailwind does support Vite without vps.

I'll have a look at this.

**Comment by AaronBeaudoin** [comment]
So I took a look at this and played around some more, and it looks like the issue is related specifically to Vue SFCs (I feel like I'm running into a lot of those).

For an `index.page.client.vue` file like this:

```vue
<template>
  <div class="bg-red-500">tailwind</div>
</template>
```

I get the issue I previously described.

But if I just make a `test.page.client.js` file like this:

```js
import { h } from "vue";

export const Page = {
  render() {
    return h("div", { class: "bg-red-500" }, "tailwind");
  }
};
```

Changing the class updates Tailwind as expected.

I guess I'll take this issue to `@vitejs/plugin-vue`?

**Comment by AaronBeaudoin** [comment]
https://github.com/vitejs/vite/issues/9587

**Comment by AaronBeaudoin** [comment]
The linked issue was closed because it seems the root cause was the same as https://github.com/vitejs/vite/issues/9341.

I guess that means you can probably close this issue as well. Hopefully we'll see that fix land soon.

**Comment by brillout** [comment]
I believe it's fixed.
