### ISSUE TITLE
Using VPS With ANY Vite-Supported Setup

### ISSUE THREAD

**Issue by AaronBeaudoin** [brillout/vite-plugin-ssr#412]
### Question / Discussion

I want to start a discussion about this based on some recent issues working with atomic CSS libraries such as UnoCSS and Tailwind CSS. It seems like those tools really expect to always be running in a specific "type of environment" (client-side vs. server-side) during development and then potentially another in production or during a build. I've been thinking about this problem, and as I'm sure you'll agree, I don't think the solution it to build a VPS specific integration/solution for every specific tool. So then, **what is the solution?**

Recently during our discussion in #53 I suggested the idea of using query parameters in the URL string of an import to tell VPS what mode you want the imported asset/module to run in. I think this is the solution here as well, but with an extension. Here is what I think should be added to VPS (before all the other stuff in #53, if you agree):

- Add `mode=server` to the query string of an import to run that asset/module on the server-side.
- Add `mode=client` to the query string of an import to run that asset/module on the client-side.
- Add `mode=isomorphic` to the query string of an import to run that asset/module everywhere.
- Add `dev=[same-as-above]` to override the `mode` parameter for that asset/module only in development.

I think this should give users the flexibility to guarantee the following: If a plugin/library work with Vite _without VPS_, then using one of the above combinations it can be made to work _with VPS_ as well.

For example, for UnoCSS I could do `mode=client` in `_default.page.server.js` and everything would work. Or, if necessary, I could do `mode=server&dev=client` (optionally omitting `mode=server` because it should be implicitly set for imports in `_default.page.server.js`).

I know that generally running something different in development versus production is a bad practice, however, in this case we might potentially be working with tools that need to run in a certain mode and don't have the choice. With this solution, at least the developer has the option to get the tool of their choice working by explicitly specifying how to run it. If a discrepancy between development and production occurs then it is the fault of the developer entirely.

What do you think?

**Comment by brillout** [comment]
I believe most, if not all, issues we stumbled upon are not related to where modules are loaded.

E.g. the HMR bug and the Tailwind bug are most likley related to `@vitejs/plugin-vue`. The proper way to fix these issues is to dig into why these issues happen and, if the fix is easy, make an upstream PR. I can see the HMR bug to be easy to fix, as for the Tailwind bug, chances are that it's an easy fix as well (but not sure): it's working for React so that considerably reduces the search space (it must be something related to `@vitejs/plugin-vue` and most likely to Vue's SFCs).

I'm open to implementing such environment specifiers, which can be already useful today, but we'd need this acorn parsing package I mentioned in #53. (There is a way to implement this with Vite instead of acorn but it's fairly complex.)

**Comment by brillout** [comment]
Also, on a high-level, the vast majority of integrations work just fine. The few integration problems arise from low-level details (e.g. the clashing of query parameters), not from where modules are being loaded.

Although I share the sentiment here, I don't think it would improve things regarding integrations.

**Comment by brillout** [comment]
Closing as per previous comments. (But I'm not forgetting your proposal :-).)
