### ISSUE TITLE
Unnecessary contextProps fetch with `#` in URL, and incorrect routing via function

### ISSUE THREAD

**Issue by chrisvariety** [brillout/vite-plugin-ssr#43]
You can just call me the `#` guy...

Vite 2.1.4
vite-plugin-ssr 0.1.0-beta.33 (really appreciate all the previous fixes, library is looking really good!)

Two things I'm seeing:

1. On `vite-plugin-ssr/examples/react`, `isOriginalUrl` is returning false when navigating to `/#`, which leads to a fetch of `/index.contextProps.json`, because `/#` !== `/`. I believe this is an unnecessary and not expected fetch. https://github.com/brillout/vite-plugin-ssr/blob/a91ffcae2d8fc525202855887b7b409b752de328/src/client/navigationState.client.ts#L16-L18

2. Somewhat related as I think this would be resolved if 1 is resolved, but might be a different underlying issue. On `vite-plugin-ssr/examples/react`, define a file `index.page.route.js` that contains:

```
export default function ({ contextProps }) {
  if (contextProps.url === "/") {
    return {
      match: -1
    };
  }
  return { match: false };
}
```

Loading the index with a hash at the end, `/#`, you'll see it correctly SSRs, but during hydration it is actually matching and hydrating the error page and not the index page, which leads to a hydration error as the html doesn't match. I believe this is because `contextProps` aren't being passed to the route function during the client side routing.

**Comment by brillout** [comment]
1. Fixed. Let me know if you need a release.

2. You should use `url` instead of `contextProps.url`.

```
export default function ({ url }) {
  if (url === "/") {
    return {
      match: -1
    };
  }
  return { match: false };
}
```

But you're right `vite-plugin-ssr` should also set `contextProps.url`, out of consistency.

> You can just call me the # guy...

😂 Love it though.

**Comment by chrisvariety** [comment]
@brillout 

1. Thanks, no need!
2. ah, you're right, this is unrelated to the `#`. url was just an example for the repro, I actually have a catchall route that looks like:

```
  if (contextProps.activePage) {
    return {
      match: -2 // built-in routes should take priority
    };
  }
```

This works great when server-side transitioning, but client-side breaks. `activePage` is exposed to the client as well via `passToClient`. Is it possible to access this info while client-side transitioning in a route, or I should I move it to the `.server` file? Tricky part is that I actually want it to 404 out if it's not a valid URL. (the list of valid pages is stored in the database)

**Comment by brillout** [comment]
> the list of valid pages is stored in the database

You make a database request against that list of valid URLs on every page request, correct?

> This works great when server-side transitioning

Because you add the info to `contextProps` at the server integration point `const renderPage = createPageRender(); renderPage({ contextProps: { activePage } });`, correct?

Would enabling data to be added to `contextProps` at `useClientRouter({ onTransitionStart() {/* add stuff to contextProps */} })` work for you?

The best would be to have an isomorphic `addContextProps`, but there is currently no canonical place for it to live; and AFAICT I'd say that adding a new file page type `_default.page.iso.js` to not be worth it.

> should I move it to the .server file?

How do you see this to solve the problem? Note that routing happens exclusively on the client-side for page transitions; no server-side `contextProps` would be available to your Route Function.

**Comment by brillout** [comment]
> AFAICT I'd say that adding a new file page type _default.page.iso.js to not be worth it.

Actually, a solution would be to `export { addContextProps }` along `Page` in `*.page.js` files.

**Comment by chrisvariety** [comment]
@brillout 

Yeah, I agree adding a new `.iso.js` wouldn't be worth it. There's even some opportunity to put it all into a single file like next.js does, if you can figure out how to separate the server exports from client. Here's how they do catchalls: https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes

I think this is a fairly specific scenario of me wanting a 404 and a catchall route. I put together a little repo based on the `react` example, you can see the relevant commit here: https://github.com/chrisvariety/vite-plugin-ssr-catchall-404/commit/54e8f2957ba424eec38d1510740adbedd981bdf8

Here's some feedback based on that example... but just my opinions, feel free to ignore 😄 

- It's a little surprising `contextProps` (or even `pageProps`) are available in `.page.route.js` when server side rendering but not client side. I understand why that is now but didn't before, could be good to include in the client side routing documentation, unless I missed it.
- I haven't thought this through fully, but setting a status code from `.page.server` could be a good enhancement? Or some other way to 404 in my example. I can think of some hacks but nothing clean. 

Going to close this one out tho as this doesn't have anything to do with `#` and the original issue is fixed.

**Comment by brillout** [comment]
I see two solutions:
 - Move `addContextProps()` to `_default.page.js` or `some.page.js`: it is always called and the added `contextProps` are always provided to route functions. (It's called not only in Node.js but also in the browser). (This feature is not implemented yet but I will; it also solves another use case not discussed in this thread.)
 - Use Server-side Routing instead of Client-side Routing.

Would one of these two work for you?

> I haven't thought this through fully, but setting a status code from .page.server could be a good enhancement? Or some other way to 404 in my example. I can think of some hacks but nothing clean.

I believe this wouldn't solve the problem. The thing is that, when doing Client-side Routing, the routing happens *before* the `contextProps` are fetched from your server; the server is not involved in the routing process in any way. (This is not what you want, but there are situations where this is what should happen.)

> just my opinions, feel free to ignore 😄

No please, I very much welcome feedback and ideas.

I agree about the rest.

**Comment by brillout** [comment]
Note that `contextProps.url` is deprecated; use `contextProps.urlPathname`, `contextProps.urlFull` (and soon `contextProps.urlParsed`) instead which are available *everywhere*, including the route function, in the browser as well as Node.js.

There is some work pending about the rest of the discussion.
