### ISSUE TITLE
Code splitting issues

### ISSUE THREAD

**Issue by rivatove** [brillout/vite-plugin-ssr#475]
### Description

Hello,

Previously I split my app into two js files, vendor.js and app.js. I achieved this with the _splitVendorChunkPlugin_ and a bit of custom logic in _rollupOptions_. Right now I can't do it because _rollupOptions_ seem to get overwritten by VPS. How do I opt out of its code splitting? I use SSG (pre-rendering).

Also, I don't quite understand why these files get included in the SSG bundle, what's their use in static HTML pages? I don't use client routing either.
[https://prnt.sc/Y6LdoWF23aWa](https://prnt.sc/Y6LdoWF23aWa)
[https://prnt.sc/YqN9BdsVqPWG](https://prnt.sc/YqN9BdsVqPWG)
[https://prnt.sc/cM-6MK1akylk](https://prnt.sc/cM-6MK1akylk)

**Comment by brillout** [comment]
>  rollupOptions seem to get overwritten by VPS

Can you elaborate on that? Vps only modifies the Rollup output file names while respecting the user's Rollup config. So this shouldn't happen. See `vite-plugin-ssr/node/plugin/plugins/distFileNames.ts`.

**Comment by brillout** [comment]
This is normal because each page is getting its own entry/bundle. That's because Rollup code-split dynamic imports.

As for entry-server-routing.js, you can ignore that file as it will never be loaded since you do Client Routing.

Note that Rollup is working on a "minimal chunk size" feature so you'll be able to further bundle things together.

I think we can close this since I don't see any noticeable performance issue.
