### ISSUE TITLE
Lost assets during SSR in production build

### ISSUE THREAD

**Issue by DaniilIsupov** [brillout/vite-plugin-ssr#610]
### Description

Problem is reproduced in official example - https://github.com/brillout/vite-plugin-ssr/tree/main/examples/vue-router
It's worth noting that there is no problem when using dev server

1. cloning repository
2. `vite build` - build for production
3. `vite preview` - locally preview production build
4. look carefully at Network panel

![telegram-cloud-document-2-5377526898312095373](https://user-images.githubusercontent.com/23086234/215102932-62f2990c-be02-40ba-b9ac-c1ff7ce8e926.jpg)
![telegram-cloud-document-2-5377526898312095381](https://user-images.githubusercontent.com/23086234/215102981-b5b0fcb9-0355-4f29-be59-c137c3bc28e3.jpg)

Style `/assets/About.34547aed.css` are missing in head (`head > link[rel="stylesheet"]`)
Style are initiated from javascript

**Comment by brillout** [comment]
Indeed, all CSS should be present in `<head>`. I'll have a look at it.

**Comment by brillout** [comment]
The problem here is that only Vue Router has access to the route mapping:

https://github.com/brillout/vite-plugin-ssr/blob/2ef3fa1071a5c5f2b2f78407c02f8aefa55cbd75/examples/vue-router/pages/router.js#L10-L19

VPS doesn't know the route mapping and therefore cannot inject the CSS accordingly.

Vue Router needs to be deeply intergrated with VPS. Closing in favor of https://github.com/brillout/vite-plugin-ssr/issues/611.

**Comment by nestle49** [comment]
@brillout 
I have the same problem, finally after migration our SPA from nuxt to vite-ssr-plugin, its give very low CLS and destroyed pagespeed metrics, indicators 30% more before. We have dynamically app with asyncComponent, that blocked any solution that I can think. Maybe can u any ideas?

**Comment by brillout** [comment]
@nestle49 PM me on Discord.
